{
  "keywords": [
      "openstack",
      "nova",
      "css"
  ],
  "proxies": [
      "51.75.147.43:3128",
      "51.75.147.41:3128",
      "136.243.254.196:80",
      "62.23.15.92:3128"
  ],
  "type": "Repositories"
}